---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: log-detective-website
spec:
  selector:
    matchLabels:
      component: log-detective-website
  template:
    metadata:
      labels:
        component: log-detective-website
    spec:
      volumes:
        - name: persistent
          persistentVolumeClaim:
            claimName: persistent
      containers:
        - name: log-detective-website
          image: quay.io/jkadlcik/log-detective:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: persistent
              mountPath: /persistent
          resources:
            requests:
              memory: "400Mi"
              cpu: "50m"
            limits:
              memory: "800Mi"
              cpu: "1"
  replicas: 1
  strategy:
    type: Recreate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: persistent
  name: persistent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
kind: Service
apiVersion: v1
metadata:
  name: log-detective-website
spec:
  ports:
    - name: log-detective-website
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    component: log-detective-website
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: log-detective-website
  namespace: communishift-log-detective
spec:
  host: >-
    log-detective-website-communishift-log-detective.apps.fedora.cj14.p1.openshiftapps.com
  to:
    kind: Service
    name: log-detective-website
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status: {}
