---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: logdetective-website
spec:
  selector:
    matchLabels:
      component: log-detective-website
  template:
    metadata:
      labels:
        component: log-detective-website
    spec:
      volumes:
        - name: persistent
          persistentVolumeClaim:
            claimName: persistent
      containers:
        - name: logdetective-website
          image: quay.io/logdetective/website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: persistent
              mountPath: /persistent
          resources:
            requests:
              memory: "400Mi"
              cpu: "50m"
            limits:
              memory: "800Mi"
              cpu: "500m"
  replicas: 1
  strategy:
    type: Recreate
---
# communityshift allows only a single PVC :(((((
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: persistent
  name: persistent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: Service
apiVersion: v1
metadata:
  name: logdetective-website
spec:
  ports:
    - name: logdetective-website
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    component: log-detective-website
---
# Route stuff stolen from Packit:
# https://github.com/packit/deployment/blob/main/openshift/packit-service.yml.j2#L147
# Gunicorn can't do 2 domains at the same time, we need nginx for that:
#   https://github.com/fedora-copr/logdetective-website/issues/61
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: log-detective-website
spec:
  host: log-detective.com
  to:
    kind: Service
    name: logdetective-website
  port:
    targetPort: logdetective-website
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: log-detective-website-www
spec:
  host: www.log-detective.com
  to:
    kind: Service
    name: logdetective-website
  port:
    targetPort: logdetective-website
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: logdetective-website
spec:
  host: logdetective.com
  to:
    kind: Service
    name: logdetective-website
  port:
    targetPort: logdetective-website
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: logdetective-website-www
spec:
  host: www.logdetective.com
  to:
    kind: Service
    name: logdetective-website
  port:
    targetPort: logdetective-website
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
