name: Test backend

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Install dependencies
        run: |
          sudo apt-get install make
      - name: Test backend inside container
        run: |
          make test-backend-in-container
        shell: bash
